_target_: pytorch_lightning.Trainer
callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    save_last: True
logger:
  - _target_: pytorch_lightning.loggers.TensorBoardLogger
    save_dir: output/tb_logs
    version: ${experiment_name}
accelerator: gpu
devices: 1
max_epochs: 200
accumulate_grad_batches: 1